### PR TITLE
Update TS Config to support new decorators model definition

### PR DESCRIPTION
**Pull request by johneatmon**
Based on [this issue](https://github.com/sequelize/website/issues/552) and [this issue](https://github.com/sequelize/sequelize/issues/16866).

Update `tsconfig.json`:
- Add support for `experimentalDecorators`
- Bump module and moduleResolution to import `@sequelize/core/decorators-legacy` declarations properly

Update `sscce-sequelize-7.ts`:
- Add new Bar model to demonstrate new model definition example with decorators

### CODE REVIEW

**Comment by johneatmon** [comment]
Node 14 tests failed for syntax error (makes sense because `??=` is Node 15+, IIRC). Though, curiously, SQLite test for Node 16 failed for the same reason.

Not sure if the other failures are related to my change; if someone wants to take a look and let me know, happy to update my PR. 😊

**Comment by WikiRik** [comment]
SQLite on Node 16 fails due to a typo, the following line should be using `${{ matrix.node}}`;
https://github.com/sequelize/sequelize-sscce/blob/a8ce25ff1f8edb61ade5a9ae3749843e41a20a50/.github/workflows/ci.yml#L26

I fixed that in #261 but I forgot to look into the failing tests on there so we didn't merge that yet

**Comment by WikiRik** [comment]
I've updated #261 and the CI is passing there. Can you base your branch on that PR and see if the CI passes still with your updates?

**Comment by WikiRik** [comment]
@ephys did you close this on purpose? Or did this get auto-closed because you merged my PR?

**Comment by ephys** [comment]
It was closed by the merge of your PR as the target branch was deleted

**Comment by WikiRik** [comment]
Ah yes, that's what I thought. The mobile app you mentioned that you closed as completed.

@johneatmon can you change the target branch to main and reopen this branch?

**Comment by johneatmon** [comment]
@WikiRik tbh I'm not sure how to do it with this existing pull, do I have to reopen?

**Comment by WikiRik** [comment]
@johneatmon not sure if you can just update the target branch and reopen. If not, you might need to open a new PR with the same changes.

**Comment by johneatmon** [comment]
@WikiRik re-opened in #272

**Pull request closed without merging**
