### PR TITLE
Updating runner to use database versions and CI comparable to v7

### PR DESCRIPTION
**Pull request by WikiRik**
Fixes https://github.com/sequelize/sequelize/issues/16434

This PR overhauls this repo once again.
- CI is updated to use Node 10, 18, 20 (oldest v6, oldest v7, latest LTS). It started out as a copy of the CI on the core repo but the install-and-build artifact has been removed and prepare-ci/run SSCCE was added.
- The setup folder is renamed to dev, to reflect the core repo. I also copied over the oldest/latest from there. We can update the oldest to the oldest supported v6 versions of the databases but I didn't think that was necessary as we only had one version before.
- yarn.lock was added for the cache of GitHub Actions but I'm open to not using that feature and removing it again

In a future PR we should add DB2 support, this PR is already too large as it is.

And we should maybe consider deprecating this repo and updating SSCCE functionality in v6/main branches of the core repo and add a GitHub action that automatically tags a PR that (only) updates the SSCCE. That way we can easily filter out the SSCCE PRs and we don't have to maintain two separate versions.

### CODE REVIEW

**Review by Hornwitser — APPROVED** [review]
Looks good, but there is still the issue that tests for v7 try to run on database versions that are unsupported. For example the postgres ones run on 9.5 and 10, but according to https://sequelize.org/releases/ only 11 and up is supported.

**Comment by WikiRik** [comment]
> Looks good, but there is still the issue that tests for v7 try to run on database versions that are unsupported. For example the postgres ones run on 9.5 and 10, but according to [sequelize.org/releases](https://sequelize.org/releases/) only 11 and up is supported.

Good point! We've updated files surrounding that in the sequelize repo for usage in the CI, but haven't updated that here. That shouldn't be why some of these tests are failing but I'll look into that later.

**Comment by WikiRik** [comment]
Update; I think it is indeed the postgres and MySQL versions that cause this to break. I'll need to update this with the files from the core repo.

**Review by Hornwitser — COMMENTED** [review]
This is too involved with databases and CI tools I'm not familiar with for me to review.

**Comment by ephys** [comment]
Pretty great to see an update in this repository
We could merge this as-is, but I think we should consider splitting the "oldest" dialects into oldest-v7 and oldest-v6 (latest doesn't need to be split as both versions support the latest version of databases)

**Comment by WikiRik** [comment]
Good idea! I'll look into that for the next PR

**Review by ephys — APPROVED** [review]

**Pull request merged**
